Add an option to generate JSDoc-style comments
d-kimuson/type-predicates-generator pull request #2
Opened 2021-12-04 11:53 UTC by yudai-nkt

Fix #1. I didn't add a test against my commits because I couldn't find one for the `generateTypePredicates` function.

FYR, below are the example comments generated with this PR.

<details>
<summary>diff of the generated code w/ and w/o the <code>--comment</code> option</summary>

```diff
diff --git a/example/type-predicates.ts b/example/type-predicates.ts
index fc7f697..10daef5 100644
--- a/example/type-predicates.ts
+++ b/example/type-predicates.ts
@@ -38,113 +38,403 @@ const isUnion = (unionChecks: ((value: unknown) => boolean)[]) =>
   (value: unknown): boolean =>
     unionChecks.reduce((s: boolean, isT) => s || isT(value), false)
 
+/**
+  * Check if a variable is of type {@link ArrStr} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @param checkOpt Whether to check all elements of the array or only the first one.
+  * @return `true` if the argument is of type {@link ArrStr}, `false` otherwise.
+  */
 export const isArrStr = (arg_0: unknown, checkOpt: ArrayCheckOption = 'all'): arg_0 is ArrStr => isArray(isString, checkOpt)(arg_0);
+/**
+  * Assert if a variable is of type {@link ArrStr} and throws a TypeError if the assertion fails.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param value Argument to inspect.
+  * @throw TypeError if the given argument is not compatible with the type {@link ArrStr}.
+  */
 export function assertIsArrStr(value: unknown): asserts value is ArrStr {
   if (!isArrStr(value)) throw new TypeError(`value must be ArrStr but received ${value}`)
 };
+/**
+  * Check if a variable is of type {@link ArrStr2} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @param checkOpt Whether to check all elements of the array or only the first one.
+  * @return `true` if the argument is of type {@link ArrStr2}, `false` otherwise.
+  */
 export const isArrStr2 = (arg_0: unknown, checkOpt: ArrayCheckOption = 'all'): arg_0 is ArrStr2 => isArray(isString, checkOpt)(arg_0);
+/**
+  * Assert if a variable is of type {@link ArrStr2} and throws a TypeError if the assertion fails.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param value Argument to inspect.
+  * @throw TypeError if the given argument is not compatible with the type {@link ArrStr2}.
+  */
 export function assertIsArrStr2(value: unknown): asserts value is ArrStr2 {
   if (!isArrStr2(value)) throw new TypeError(`value must be ArrStr2 but received ${value}`)
 };
+/**
+  * Check if a variable is of type {@link ArrInProp} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @return `true` if the argument is of type {@link ArrInProp}, `false` otherwise.
+  */
 export const isArrInProp = (arg_0: unknown): arg_0 is ArrInProp => isObject(arg_0) &&
   ('arr' in arg_0 && ((arg_1: unknown): boolean => isArray(isString)(arg_1))(arg_0['arr']));
+/**
+  * Assert if a variable is of type {@link ArrInProp} and throws a TypeError if the assertion fails.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param value Argument to inspect.
+  * @throw TypeError if the given argument is not compatible with the type {@link ArrInProp}.
+  */
 export function assertIsArrInProp(value: unknown): asserts value is ArrInProp {
   if (!isArrInProp(value)) throw new TypeError(`value must be ArrInProp but received ${value}`)
 };
+/**
+  * Check if a variable is of type {@link Complex} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @return `true` if the argument is of type {@link Complex}, `false` otherwise.
+  */
 export const isComplex = (arg_0: unknown): arg_0 is Complex => isObject(arg_0) &&
   (((arg_1: unknown): boolean => isUnion([isUndefined, isString])(arg_1))(arg_0['name'])) && (((arg_1: unknown): boolean => isUnion([isUndefined, isString])(arg_1))(arg_0['password']));
+/**
+  * Assert if a variable is of type {@link Complex} and throws a TypeError if the assertion fails.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param value Argument to inspect.
+  * @throw TypeError if the given argument is not compatible with the type {@link Complex}.
+  */
 export function assertIsComplex(value: unknown): asserts value is Complex {
   if (!isComplex(value)) throw new TypeError(`value must be Complex but received ${value}`)
 };
+/**
+  * Check if a variable is of type {@link User} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @return `true` if the argument is of type {@link User}, `false` otherwise.
+  */
 export const isUser = (arg_0: unknown): arg_0 is User => isObject(arg_0) &&
   ('id' in arg_0 && (isNumber)(arg_0['id'])) && ('firstName' in arg_0 && (isString)(arg_0['firstName'])) && ('lastName' in arg_0 && (isString)(arg_0['lastName']));
+/**
+  * Assert if a variable is of type {@link User} and throws a TypeError if the assertion fails.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param value Argument to inspect.
+  * @throw TypeError if the given argument is not compatible with the type {@link User}.
+  */
 export function assertIsUser(value: unknown): asserts value is User {
   if (!isUser(value)) throw new TypeError(`value must be User but received ${value}`)
 };
+/**
+  * Check if a variable is of type {@link ResultOfGenerics} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @return `true` if the argument is of type {@link ResultOfGenerics}, `false` otherwise.
+  */
 export const isResultOfGenerics = (arg_0: unknown): arg_0 is ResultOfGenerics => isObject(arg_0) &&
   (((arg_1: unknown): boolean => isUnion([isUndefined, isNumber])(arg_1))(arg_0['id'])) && (((arg_1: unknown): boolean => isUnion([isUndefined, isDate])(arg_1))(arg_0['time']));
+/**
+  * Assert if a variable is of type {@link ResultOfGenerics} and throws a TypeError if the assertion fails.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param value Argument to inspect.
+  * @throw TypeError if the given argument is not compatible with the type {@link ResultOfGenerics}.
+  */
 export function assertIsResultOfGenerics(value: unknown): asserts value is ResultOfGenerics {
   if (!isResultOfGenerics(value)) throw new TypeError(`value must be ResultOfGenerics but received ${value}`)
 };
+/**
+  * Check if a variable is of type {@link Hello} and narrow it down to that type if the check passes.
+  * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
+  * @param arg_0 Argument to inspect.
+  * @retu [...]

2021-12-05 12:08 UTC, d-kimuson requested changes
@yudai-nkt  Thank you for the feature suggestion and pull request, I was just wondering about the JSDoc format, please check!

2021-12-05 12:08 UTC, d-kimuson commented on src/generate/generate-type-predicates.ts
> +  */
It seems to be slightly different from the [JSDoc](https://jsdoc.app/about-getting-started.html) format.
How about the following?

```suggestion
/**
 * Assert if a variable is of type {@link ${typeName}} and throws a TypeError if the assertion fails.
 * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
 * @param value Argument to inspect.
 * @throw TypeError if the given argument is not compatible with the type {@link ${typeName}}.
 */
```

2021-12-05 12:08 UTC, d-kimuson commented on src/generate/generate-type-predicates.ts
> +  */
also here

```suggestion
/**
 * Check if a variable is of type {@link ${typeName}} and narrow it down to that type if the check passes.
 * This function is automatically generated using [type-predicates-generator](https://www.npmjs.com/package/type-predicates-generator).
 * @param arg_0 Argument to inspect.${
    type.__type === "ArrayTO"
      ? "\n * @param checkOpt Whether to check all elements of the array or only the first one."
      : ""
  }
 * @return \`true\` if the argument is of type {@link ${typeName}}, \`false\` otherwise.
 */
```

2021-12-05 13:40 UTC, yudai-nkt commented
Thanks for the review and good catch! Suggestions applied.

2021-12-08 11:27 UTC, d-kimuson commented
@yudai-nkt 
Sorry for the delay, and thanks for the fix! I'll merge them.

I want to write changelog when I have time, so I'll publish it to npm  and let you know when it's ready.
Please wait for a while.

2021-12-08 11:27 UTC, merged

2021-12-10 14:59 UTC, d-kimuson commented
@yudai-nkt Thanks for contributing! I've just released v0.3.1 which reflects this PR!